name: TDasset Docs Check and Build

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  pull-requests: write

jobs:
  check-docs:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install markdownlint
        run: sudo npm install -g markdownlint-cli

      - name: Markdown Lint
        run: markdownlint -c .github/workflows/markdown_config.json ./

      - name: Typos Check (zh config)
        uses: crate-ci/typos@v1.31.1
        with:
          files: 'docs/**/*.md'
          config: .github/workflows/typos.toml
          
      - name: check docs linter-formatter using AutoCorrect
        uses: huacnlee/autocorrect-action@v2
        with:
          args: --lint docs/**/*.md

      - name: Report ReviewDog
        if: always()
        uses: tomchon/autocorrect-action@fix/review-dog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewdog: true
          args: ./docs/**/*.md

  build-doc:
    needs:
      - check-docs
    uses: ./.github/workflows/common_build.yaml
    with:
      build_docs: true