name: Deploy Docs

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/deploy_docs.yaml'
      - '.docsearch/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common_build.yaml
    with:
      build_docs: true
      
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: upload docs to Azure Blob Storage
      uses: azure/cli@v2
      with:
        azcliversion: 2.73.0
        inlineScript: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --destination '$web' \
            --source build \
            --overwrite \
            --auth-mode key
          echo "Uploaded EN docs to Azure Blob Storage"

    - name: purge Azure CDN endpoint
      uses: azure/cli@v2
      with:
        azcliversion: 2.73.0
        inlineScript: |
          az cdn endpoint purge \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --profile-name ${{ secrets.AZURE_CDN_PROFILE }} \
            --name ${{ secrets.AZURE_CDN_ENDPOINT }} \
            --content-paths  "/*" "/index.html" "/"
          echo "Azure CDN purged for docs.tdasset.ai"

    - name: Run docsearch-scraper
      env:
        APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      run: |
        CONFIG="$(cat ${{ github.workspace }}/.docsearch/tdasset.json | jq -c '.')"
        docker run --rm \
          -e APPLICATION_ID \
          -e API_KEY \
          -e CONFIG="$CONFIG" \
          algolia/docsearch-scraper